// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fft_get_level_from_bounds_two_sided
double fft_get_level_from_bounds_two_sided(const std::vector<double>& b, const std::vector<double>& B);
RcppExport SEXP _qqconf_fft_get_level_from_bounds_two_sided(SEXP bSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(fft_get_level_from_bounds_two_sided(b, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qqconf_fft_get_level_from_bounds_two_sided", (DL_FUNC) &_qqconf_fft_get_level_from_bounds_two_sided, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_qqconf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
